#!/usr/bin/php
<?php

use Itomori\Cli\Itomori;
use Itomori\Autoloader;

define('TEST', dirname(__FILE__));

require_once TEST.'/Autoloader.php';

Autoloader::register();

$cli = new Itomori();
$cli->run();
